### ISSUE TITLE
Node does not fully start

### ISSUE THREAD

**Issue by MCFurry** [nobleo/nobleo_socketcan_bridge#9]
Since the name change of this package, the composable node seems to work fine, but starting the node standalone doesn't seem to work.
It also doesn't show in `ros2 node list`.

**Comment by Rayman** [comment]
I've just tested this on jazzy, and it still works. Do you get an error?

**Comment by MCFurry** [comment]
Nope no error, it tries to start but simply freezes:
`ros2 launch benchmark.launch.xml 

[INFO] [launch]: All log files can be found below /home/mcfurry/.ros/log/2024-07-25-16-46-06-832704-furbook-711249
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [ros2-1]: process started with pid [711252]
[INFO] [socketcan_bridge-2]: process started with pid [711254]
[INFO] [socketcan_bridge-3]: process started with pid [711256]
[INFO] [ros2-4]: process started with pid [711258]`


And there it stops, no nodes show when requesting `ros2 node list` and it also doesn't work...

**Comment by Rayman** [comment]
Is it only locally? Can you try to clean your build folder?

**Comment by MCFurry** [comment]
Interesting... I thought I tried a clean workspace, but inside a docker, or now on a fresh workspace it indeed seems to start just fine...
I'll double test on our robot and close the issue if it works fine there!

**Comment by MCFurry** [comment]
Confirmed, a clean workspace does not give any issues, so the package itself is fine! Thx for thinking along!
